# This file was generated by GoReleaser. DO NOT EDIT.
cask "kite" do
  version "0.1.5"

  on_macos do
    on_intel do
      sha256 "45d65b6d94c59eb7052023970f08b3efd9003b4487368043b58dc9d253cc8a54"
      url "https://github.com/Gandalf-Le-Dev/kite/releases/download/v#{version}/kite_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fb0d73c5aa7a7eff91d7aa9787b651ca453713b34fe8d52125bb34a049df0210"
      url "https://github.com/Gandalf-Le-Dev/kite/releases/download/v#{version}/kite_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b149bee3ec96cbc66d076bdc7d43bebc44b30f7795d4b2e6e491d1dd23f8c462"
      url "https://github.com/Gandalf-Le-Dev/kite/releases/download/v#{version}/kite_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f1f81f275dbf0be68ca324dcdd6a70c190614af4b19a944d3e12bd9fceb249d3"
      url "https://github.com/Gandalf-Le-Dev/kite/releases/download/v#{version}/kite_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kite"
  desc "One self-hosted Go binary for file transfer, hosted sharing, and pastes"
  homepage "https://github.com/Gandalf-Le-Dev/kite"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kite"

  postflight do
    # Downloaded binaries carry a quarantine attribute, and Gatekeeper
    # refuses to run them until it is cleared.
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kite"]
    end
  end

  # No zap stanza required

end
