# This file was generated by GoReleaser. DO NOT EDIT.
cask "kite" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "ca62937b6d020ca829d63f77f6720e7c5a341ce4fd835168e5b6d8256cfd1641"
      url "https://github.com/Gandalf-Le-Dev/kite/releases/download/v#{version}/kite_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2584eb11c5f2af0cdb20eb8b6dc73aa43d1314b196ced449f7025e6f018a27f3"
      url "https://github.com/Gandalf-Le-Dev/kite/releases/download/v#{version}/kite_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4ae101b3cde8fe207ca5fbe57558203227ff129a784f5f19754cca9e25a7ea3d"
      url "https://github.com/Gandalf-Le-Dev/kite/releases/download/v#{version}/kite_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b6cc1b8c2d3e4f3e0b1d743a91e8b3696720e2f62e3da786eb84106b755e90bc"
      url "https://github.com/Gandalf-Le-Dev/kite/releases/download/v#{version}/kite_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kite"
  desc "One self-hosted Go binary for file transfer, hosted sharing, and pastes"
  homepage "https://github.com/Gandalf-Le-Dev/kite"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kite"

  postflight do
    # Downloaded binaries carry a quarantine attribute, and Gatekeeper
    # refuses to run them until it is cleared.
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kite"]
    end
  end

  # No zap stanza required

end
