# This file was generated by GoReleaser. DO NOT EDIT.
cask "pilot" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "869c9fc08bb5433ecf032fcece88663dbc78425e33dd360542974c52bf98ea14"
      url "https://github.com/Gandalf-Le-Dev/pilot/releases/download/v#{version}/pilot_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c572df5ad6e21cdcce27cddc25e17f7ee18ac754fd5b71c0566ce32605dbfbd9"
      url "https://github.com/Gandalf-Le-Dev/pilot/releases/download/v#{version}/pilot_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "09c371f84f434a2d6e91f68fecb56c9649c6918d016130e25f776a8abdd63701"
      url "https://github.com/Gandalf-Le-Dev/pilot/releases/download/v#{version}/pilot_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "053f4192e483d03c212891293a08b6950a9359df4e6440188723d0ce0c044feb"
      url "https://github.com/Gandalf-Le-Dev/pilot/releases/download/v#{version}/pilot_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pilot"
  desc "Monitor, deploy, and update the services on a small fleet of servers"
  homepage "https://github.com/Gandalf-Le-Dev/pilot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pilot"

  postflight do
    # Downloaded binaries carry a quarantine attribute, and Gatekeeper
    # refuses to run them until it is cleared.
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pilot"]
    end
  end

  # No zap stanza required

end
