# This file was generated by GoReleaser. DO NOT EDIT.
cask "pilot" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "5b6ba4fccfe7efdc1fd1825a7154ba90a03e341c2ca526301ca3027de2e34901"
      url "https://github.com/Gandalf-Le-Dev/pilot/releases/download/v#{version}/pilot_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "64c151826b053f00116c664e5e46f815ef32f293113bef4e1d077e2692eb078c"
      url "https://github.com/Gandalf-Le-Dev/pilot/releases/download/v#{version}/pilot_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7ebd7919e1259a20c4a67adb1d7e41d0d3bb36746451472bad72459c60038bcf"
      url "https://github.com/Gandalf-Le-Dev/pilot/releases/download/v#{version}/pilot_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7b0dbf8b3a3d3b261eda1696a191b6b0d130ef91d7690f6cecd27ffbdbe9a8a2"
      url "https://github.com/Gandalf-Le-Dev/pilot/releases/download/v#{version}/pilot_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pilot"
  desc "Monitor, deploy, and update the services on a small fleet of servers"
  homepage "https://github.com/Gandalf-Le-Dev/pilot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pilot"

  postflight do
    # Downloaded binaries carry a quarantine attribute, and Gatekeeper
    # refuses to run them until it is cleared.
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pilot"]
    end
  end

  # No zap stanza required

end
