# This file was generated by GoReleaser. DO NOT EDIT.
cask "pilot" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "a18a21aee487bf111f5af24ae8b7760534743814dbec0ff0a31e3d2114f44730"
      url "https://github.com/Gandalf-Le-Dev/pilot/releases/download/v#{version}/pilot_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "51aa75f4a706df5e5064014f1f0794c87b25830d4fe7fc594bf6237738ef15c0"
      url "https://github.com/Gandalf-Le-Dev/pilot/releases/download/v#{version}/pilot_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2dfd471c01a12a34bea6e7eaa2a1bd750c0b9a8e04456aca9268f2efdeed78d9"
      url "https://github.com/Gandalf-Le-Dev/pilot/releases/download/v#{version}/pilot_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2fe7246228bcf604f36fe08cb30bdf02ecc50fd40a48e082f968bd5ca819481d"
      url "https://github.com/Gandalf-Le-Dev/pilot/releases/download/v#{version}/pilot_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pilot"
  desc "Monitor, deploy, and update the services on a small fleet of servers"
  homepage "https://github.com/Gandalf-Le-Dev/pilot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pilot"

  postflight do
    # Downloaded binaries carry a quarantine attribute, and Gatekeeper
    # refuses to run them until it is cleared.
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pilot"]
    end
  end

  # No zap stanza required

end
