# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kite < Formula
  desc "One self-hosted Go binary for file transfer, hosted sharing, and pastes"
  homepage "https://github.com/Gandalf-Le-Dev/kite"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Gandalf-Le-Dev/kite/releases/download/v0.1.1/kite_0.1.1_darwin_amd64.tar.gz"
      sha256 "94882edabfcb0018cbd53feba23af4d812d7cbfed7c99a6f07f11e68559dd116"

      define_method(:install) do
        bin.install "kite"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Gandalf-Le-Dev/kite/releases/download/v0.1.1/kite_0.1.1_darwin_arm64.tar.gz"
      sha256 "aab6bca5ec1706bfea4337bd4442d8514f180c6f9b814adf5ac6467539bb3d82"

      define_method(:install) do
        bin.install "kite"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Gandalf-Le-Dev/kite/releases/download/v0.1.1/kite_0.1.1_linux_amd64.tar.gz"
      sha256 "99cbf1c9ce4329e527a22632d66a908f82b98ed62cdd1105e4fc49e5adc77b67"
      define_method(:install) do
        bin.install "kite"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Gandalf-Le-Dev/kite/releases/download/v0.1.1/kite_0.1.1_linux_arm64.tar.gz"
      sha256 "fd0d50d394e12744eeeeebde810407e6c9f861f99ad9918e9272cb642acf587d"
      define_method(:install) do
        bin.install "kite"
      end
    end
  end

  test do
    system "#{bin}/kite", "version"
  end
end
