# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kite < Formula
  desc "One self-hosted Go binary for file transfer, hosted sharing, and pastes"
  homepage "https://github.com/Gandalf-Le-Dev/kite"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Gandalf-Le-Dev/kite/releases/download/v0.1.2/kite_0.1.2_darwin_amd64.tar.gz"
      sha256 "5a065d1898e6b821a6c5b574671b2a828cf3cd405bd8c704902b602e29cd9697"

      define_method(:install) do
        bin.install "kite"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Gandalf-Le-Dev/kite/releases/download/v0.1.2/kite_0.1.2_darwin_arm64.tar.gz"
      sha256 "967653498f55f0e268eb23b3d581842b1f51f1cb4f8d7ffc61131f3937f00871"

      define_method(:install) do
        bin.install "kite"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Gandalf-Le-Dev/kite/releases/download/v0.1.2/kite_0.1.2_linux_amd64.tar.gz"
      sha256 "a1df16e093eccbabba7b30cda4266836b697c21b1a875239d8600d5104616886"
      define_method(:install) do
        bin.install "kite"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Gandalf-Le-Dev/kite/releases/download/v0.1.2/kite_0.1.2_linux_arm64.tar.gz"
      sha256 "f6a98213af2f32f37ade2804186755a297b6dfa884bf7217c9e48d1c10db897d"
      define_method(:install) do
        bin.install "kite"
      end
    end
  end

  test do
    system "#{bin}/kite", "version"
  end
end
